export const INIT_WIDGET = 'WIDGET/INIT_WIDGET'
export const INIT_WIDGET_SUCCESS = 'WIDGET/INIT_WIDGET_SUCCESS'
export const INIT_WIDGET_ERROR = 'WIDGET/INIT_WIDGET_ERROR'
export const SET_ACTIVE_CONTAINER = 'WIDGET/SET_ACTIVE_CONTAINER'
