version: "3"
services:
  app:
    build: ./app
    volumes:
      - './app:/app'
      - '/app/node_modules'
    environment:
      - PORT=3000
  widget:
    build: ./widget
    volumes:
      - './widget:/app'
      - '/app/node_modules'
  nginx:
    build: ./app/nginx
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
