version: "3"
services:
  nextjs:
    build: ./promptli/
    volumes:
      - './promptli:/app'
      - '/app/node_modules'
    environment:
      - PORT=3000
  widget:
    build: ./promptli-widget
    volumes:
      - './promptli-widget:/app'
      - '/app/node_modules'
  nginx:
    build: ./promptli/nginx
    depends_on:
      - nextjs
    ports:
      - 80:80
      - 443:443
