version: "3"
services:
  api:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - MOGNGO_URI:mongodb://db:27017
      - PORT:5000
    depends_on:
      - db
    volumes:
      - "./server:/home/node/app/server"
      - "/app/server/node_modules"
    command: yarn dev
    container_name: api
    links:
      - db

  client:
    build: ./client
    stdin_open: true
    expose:
      - 3000
    environment:
      - REACT_APP_PORT:3000
      - REACT_APP_WDS_SOCKET_HOST:3000
      - REACT_APP_HOST:0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - "./client:/home/node/app/client"
      - "/app/client/node_modules"
    command: yarn start
    links:
      - api
    container_name: client

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo_db
