version: "3"
services:
  api:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - "./server:/server"
    command: yarn dev
    container_name: api

  client:
    build: ./client
    stdin_open: true
    expose:
      - 3000
    environment:
      - REACT_APP_PORT:3000
    ports:
      - 3000:3000
    volumes:
      - "./client/src:/client/src"
      - "./client/public:/client/public"
    command: yarn start
    links:
      - api
    container_name: client

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo_db
