export const FETCH_CATEGORIES = 'CATEGORIES/FETCH_CATEGORIES'
export const FETCH_CATEGORIES_REQUEST = 'CATEGORIES/FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'CATEGORIES/FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'CATEGORIES/FETCH_CATEGORIES_FAILURE'

export const FILTER_CATEGORIES = 'CATEGORIES/FILTER_CATEGORIES'
export const SELECT_ACTIVE_CATEGORY = 'CATEGORIES/SELECT_ACTIVE_CATEGORY'
