export const dashboardActionTypes = {
  INIT_DASHBOARD_REQUEST: 'DASHBOARD/INIT_DASHBOARD_REQUEST',
  INIT_DASHBOARD_SUCCESS: 'DASHBOARD/INIT_DASHBOARD_SUCCESS',
  INIT_DASHBOARD_FAILURE: 'DASHBOARD/INIT_DASHBOARD_FAILURE',
  DASHBOARD_READY: 'DASHBOARD/DASHBOARD_READY',

  CONNECT_GOOGLE_ACCOUNT: 'DASHBOARD/CONNECT_GOOGLE_ACCOUNT',
  CONNECT_GOOGLE_ACCOUNT_REQUEST: 'DASHBOARD/CONNECT_GOOGLE_ACCOUNT_REQUEST',
  CONNECT_GOOGLE_ACCOUNT_FAILURE: 'DASHBOARD/CONNECT_GOOGLE_ACCOUNT_FAILURE',
  CONNECT_GOOGLE_ACCOUNT_SUCCESS: 'DASHBOARD/CONNECT_GOOGLE_ACCOUNT_SUCCESS',

  CREATE_ITEM_REQUEST: 'DASHBOARD/CREATE_ITEM_REQUEST',
  CREATE_ITEM_SUCCESS: 'DASHBOARD/CREATE_ITEM_SUCCESS',
  CREATE_ITEM_FAILURE: 'DASHBOARD/CREATE_ITEM_FAILURE',

  CREATE_CATEGORY_REQUEST: 'DASHBOARD/CREATE_CATEGORY_REQUEST',
  CREATE_CATEGORY_SUCCESS: 'DASHBOARD/CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_FAILURE: 'DASHBOARD/CREATE_CATEGORY_FAILURE',
}
