export const SET_ITEMS_VIEW = 'ITEMS/SET_ITEMS_VIEW'

export const SET_ITEMS = 'ITEMS/SET_ITEMS'
export const SET_ITEM = 'ITEMS/SET_ITEM'
export const SELECT_ITEM = 'ITEMS/SELECT_ITEM'
export const REMOVE_ITEM = 'ITEMS/REMOVE_ITEM'
