const express = require('express')
const router = express.Router()
const userRoutes = require('./userRoutes')
const accountRoutes = require('./AccountRoutes')
const authRoutes = require('./AuthRoutes')
const dashboardRoutes = require('./Dashboard')
const itemsRoutes = require('./Items')
const reservationManagerRoutes = require('./ReservationManager')
const oauthRoutes = require('./Oauth')
const widgetConfigRoutes = require('./WidgetConfig')
const passport = require('passport')
const publicApiRoutes = require('../api')

router.use('/auth', authRoutes)
router.use('/user', userRoutes)
router.use('/account', passport.authenticate('jwt'), accountRoutes)
router.use('/dashboard', passport.authenticate('jwt'), dashboardRoutes)
router.use('/items', passport.authenticate('jwt'), itemsRoutes)
router.use('/widget-config', passport.authenticate('jwt'), widgetConfigRoutes)
router.use('/bookings', reservationManagerRoutes)
router.use('/oauth', oauthRoutes)
router.use('/public/v1', publicApiRoutes)

module.exports = router
