export const loginActionTypes = {
    LOGIN_REQUEST: 'LOGIN/LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN/LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN/LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGIN/LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGIN/LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGIN/LOGOUT_FAILURE',

    CHECK_AUTH: 'LOGIN/CHECK_AUTH',
    AUTH_SUCCESS: 'LOGIN/AUTH_SUCCESS',
    AUTH_FAILURE: 'LOGIN/AUTH_FAILURE',

    CREATE_USER_REQUEST: 'LOGIN/CREATE_USER_REQUEST',
    CREATE_USER_SUCCESS: 'LOGIN/CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: 'LOGIN/CREATE_USER_FAILURE',

    FORGOT_PASSWORD_REQUEST: 'LOGIN/FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'LOGIN/FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'LOGIN/FORGOT_PASSWORD_FAILURE',

    RESET_PASSWORD_REQUEST: 'LOGIN/RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'LOGIN/RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'LOGIN/RESET_PASSWORD_FAILURE',
}
